FROM postgres:latest


COPY ./init.db.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init.db.sh

RUN echo "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;" >> /docker-entrypoint-initdb.d/init.db.sh
RUN echo "GRANT ALL PRIVILEGES ON SCHEMA public TO $POSTGRES_USER;" >> /docker-entrypoint-initdb.d/init.db.sh
RUN echo "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRES_USER;" >> /docker-entrypoint-initdb.d/init.db.sh
RUN echo "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_USER;" >> /docker-entrypoint-initdb.d/init.db.sh
RUN echo "GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $POSTGRES_USER;" >> /docker-entrypoint-initdb.d/init.db.sh


