#!/bin/bash
set -e

# Create the database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $POSTGRES_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_NAME TO $POSTGRES_USER;
    CREATE USER myuser WITH PASSWORD "$POSTGRES_PASSWORD";
    ALTER USER myuser CREATEDB;
EOSQL
