# Generated by Django 4.2.2 on 2023-06-27 02:21

import core.models.sku
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SKU",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_deleted", models.BooleanField(default=False)),
                ("sku", models.CharField(max_length=12, unique=True)),
            ],
            options={
                "verbose_name": "SKU",
                "verbose_name_plural": "SKUs",
            },
        ),
    ]
