# Generated by Django 4.2.2 on 2023-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
            },
        ),
    ]
