# Generated by Django 4.2.2 on 2023-06-19 19:00

import core.models.sku
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku',
            field=models.CharField(default=core.models.sku.get_random_sku, max_length=12, unique=True),
        ),
    ]
