# Generated by Django 4.2.2 on 2023-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sku_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
