# Generated by Django 4.2.2 on 2023-07-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_denominations_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinfamily',
            options={'verbose_name': 'Coin Family', 'verbose_name_plural': 'Coin Families'},
        ),
        migrations.AlterModelOptions(
            name='cointypename',
            options={'verbose_name': 'Coin Type Name', 'verbose_name_plural': 'Coin Type Names'},
        ),
        migrations.AlterModelOptions(
            name='denominations',
            options={'verbose_name': 'Denomination', 'verbose_name_plural': 'Denominations'},
        ),
        migrations.AlterField(
            model_name='coinfamily',
            name='type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Clad', 'Clad'), ('Copper', 'Copper')], max_length=20),
        ),
    ]
