# Generated by Django 4.2.2 on 2023-07-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_selectmints_coinbasemodel_mint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectmints',
            old_name='west_coast',
            new_name='west_point',
        ),
    ]
