# Generated by Django 4.2.2 on 2023-07-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_rename_west_coast_selectmints_west_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectOneMint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mint_name', models.CharField(choices=[('P', 'Philadelphia Mint'), ('S', 'San Francisco Mint'), ('D', 'Denver Mint'), ('CC', 'Carson City Mint'), ('W', 'West Point Mint'), ('C', 'Charlotte Mint'), ('O', 'New Orleans Mint'), ('DL', 'Dahlonega Mint')], default='P', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='coinbasemodel',
            name='mint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mint', to='coins.selectonemint'),
        ),
        migrations.DeleteModel(
            name='SelectMints',
        ),
    ]
