# Generated by Django 4.2.2 on 2023-07-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0008_selectmints_strike_alter_selectonemint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinbasemodel',
            options={'verbose_name': 'Coin Base Model', 'verbose_name_plural': 'Coin Base Models'},
        ),
        migrations.AlterField(
            model_name='coinfamily',
            name='type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Clad', 'Clad'), ('Copper', 'Copper')], max_length=20, unique=True),
        ),
    ]
