# Generated by Django 4.2.2 on 2023-07-14 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0011_alter_coinfamily_type_alter_cointypename_coin_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('70', '70'), ('69+', '69+'), ('69', '69'), ('68+', '68+'), ('68', '68'), ('67+', '67+'), ('67', '67'), ('66+', '66+'), ('66', '66'), ('65+', '65+'), ('65', '65'), ('64+', '64+'), ('64', '64'), ('63+', '63+'), ('63', '63'), ('62+', '62+'), ('62', '62'), ('61+', '61+'), ('61', '61'), ('60+', '60+'), ('60', '60'), ('58', '58'), ('55', '55'), ('50', '50'), ('45', '45'), ('40', '40'), ('35', '35'), ('30', '30'), ('25', '25'), ('20', '20'), ('15', '15'), ('12', '12'), ('10', '10'), ('08', '08'), ('06', '06'), ('04', '04'), ('03', '03'), ('02', '02'), ('01', '01'), ('BU', 'BU'), ('CU', 'CU'), ('UNC', 'UNC'), ('AU+', 'AU+'), ('AU', 'AU'), ('XF+', 'XF+'), ('XF', 'XF'), ('VF+', 'VF+'), ('VF', 'VF'), ('F+', 'F+'), ('F', 'F'), ('VG+', 'VG+'), ('VG', 'VG'), ('G+', 'G+'), ('G', 'G')], default='70', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradingServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PCGS', 'PCGS'), ('NGC', 'NGC'), ('PCGSCAC', 'PCGS CAC'), ('NGCCAC', 'NGC CAC'), ('ANACS', 'ANACS'), ('ICG', 'ICG'), ('PCGSoNGC', 'PCGS or NGC'), ('PCGSoNGCaCAC', 'PCGS or NGC and CAC'), ('Ungraded', 'Ungraded')], default='PCGS', max_length=15, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coinbasemodel',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_services', to='coins.gradingservices'),
        ),
        migrations.AlterField(
            model_name='coinbasemodel',
            name='grading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='coins.coingrades'),
        ),
    ]
