# Generated by Django 4.2.2 on 2023-07-14 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0012_coingrades_gradingservices_alter_coinbasemodel_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coingrades',
            options={'verbose_name': 'Coin Grades', 'verbose_name_plural': 'Coin Grades'},
        ),
        migrations.AlterModelOptions(
            name='gradingservices',
            options={'verbose_name': 'Grading Service', 'verbose_name_plural': 'Grading Services'},
        ),
        migrations.AlterField(
            model_name='coinbasemodel',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_grade', to='coins.coingrades'),
        ),
        migrations.AlterField(
            model_name='coinbasemodel',
            name='grading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_service', to='coins.gradingservices'),
        ),
    ]
