# Generated by Django 4.2.2 on 2023-07-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0017_rename_family_coinfamily_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinbasemodel',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
    ]
