# Generated by Django 4.2.2 on 2023-07-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0019_coinbasemodel_mints_alter_coinbasemodel_mint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinbasemodel',
            name='mints',
        ),
        migrations.RemoveField(
            model_name='coinbasemodel',
            name='mint',
        ),
        migrations.AddField(
            model_name='coinbasemodel',
            name='mint',
            field=models.ManyToManyField(blank=True, null=True, related_name='mint', to='coins.selectonemint'),
        ),
    ]
