# Generated by Django 4.2.2 on 2023-07-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0022_alter_coinbasemodel_mint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectonemint',
            name='coin_mint',
            field=models.CharField(choices=[('Philadelphia Mint', 'Philadelphia Mint'), ('San Francisco Mint', 'San Francisco Mint'), ('Denver Mint', 'Denver Mint'), ('Carson City Mint', 'Carson City Mint'), ('West Point Mint', 'West Point Mint'), ('Charlotte Mint', 'Charlotte Mint'), ('New Orleans Mint', 'New Orleans Mint'), ('Dahlonega Mint', 'Dahlonega Mint')], default='P', max_length=32, unique=True),
        ),
    ]
