# Generated by Django 4.2.2 on 2023-08-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('images', '0002_alter_images_image'),
        ('coins', '0030_remove_coinbasemodel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MintSetTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mint_types', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MintProductsModel',
            fields=[
                ('sku_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.sku')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_bulk', models.BooleanField(default=False)),
                ('mint_set_name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=80)),
                ('year', models.IntegerField()),
                ('year2', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('quantity', models.IntegerField(default=1)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('images', models.ManyToManyField(blank=True, to='images.images')),
                ('mint', models.ManyToManyField(blank=True, related_name='mint_products', to='coins.selectonemint')),
                ('mint_set_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mint_products', to='coins.mintsettypesmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.sku', models.Model),
        ),
    ]
