# Generated by Django 4.2.2 on 2023-07-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Denominations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_of_coin', models.CharField(choices=[('$50', '$50'), ('$25', '$25'), ('$20', '$20'), ('$10', '$10'), ('$5', '$5'), ('$4', '$4'), ('$3', '$3'), ('$2.5', '$2.5'), ('$1', '$1'), ('50C', '50C'), ('25C', '25C'), ('20C', '20C'), ('10C', '10C'), ('5C', '5C'), ('3CN', '3CN'), ('3CS', '3CS'), ('2C', '2C'), ('1C', '1C'), ('H1C', 'H1C')], default='$1', max_length=4)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.coinfamily')),
            ],
        ),
        migrations.CreateModel(
            name='CoinTypeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.CharField(max_length=100)),
                ('denominations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denomination', to='coins.denominations')),
            ],
        ),
    ]
