# Generated by Django 4.2.2 on 2023-06-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilverDollars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mint', models.CharField(choices=[('P', 'Philadelphia Mint'), ('S', 'San Francisco Mint'), ('D', 'Denver Mint'), ('CC', 'Carson City Mint'), ('W', 'West Point Mint'), ('C', 'Charlotte Mint'), ('O', 'New Orleans Mint'), ('DL', 'Dahlonega Mint')], default='P', max_length=2)),
                ('pcgs_number', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('denomination', models.CharField(choices=[('$50', '$50'), ('$25', '$25'), ('$20', '$20'), ('$10', '$10'), ('$5', '$5'), ('$4', '$4'), ('$3', '$3'), ('$2.5', '$2.5'), ('$1', '$1'), ('50C', '50C'), ('25C', '25C'), ('20C', '20C'), ('10C', '10C'), ('5C', '5C'), ('3CN', '3CN'), ('3CS', '3CS'), ('2C', '2C'), ('1C', '1C'), ('H1C', 'H1C')], default='$1', max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('strike', models.CharField(choices=[('MS', 'Business/Mint State'), ('PR', 'Proof'), ('RPR', 'Reverse Proof'), ('PL', 'Proof Like'), ('DMPL', 'DMPL'), ('STN', 'Satin'), ('BRN', 'Burnished')], default='MS', max_length=4)),
                ('grading', models.CharField(choices=[('PCGS', 'PCGS'), ('NGC', 'NGC'), ('PCGSCAC', 'PCGS CAC'), ('NGCCAC', 'NGC CAC'), ('ANACS', 'ANACS'), ('ICG', 'ICG'), ('PCGSoNGC', 'PCGS or NGC'), ('PCGSoNGCaCAC', 'PCGS or NGC and CAC'), ('Ungraded', 'Ungraded')], default='PCGS', max_length=15)),
                ('grade', models.CharField(choices=[('70', '70'), ('69+', '69+'), ('69', '69'), ('68+', '68+'), ('68', '68'), ('67+', '67+'), ('67', '67'), ('66+', '66+'), ('66', '66'), ('65+', '65+'), ('65', '65'), ('64+', '64+'), ('64', '64'), ('63+', '63+'), ('63', '63'), ('62+', '62+'), ('62', '62'), ('61+', '61+'), ('61', '61'), ('60+', '60+'), ('60', '60'), ('58', '58'), ('55', '55'), ('50', '50'), ('45', '45'), ('40', '40'), ('35', '35'), ('30', '30'), ('25', '25'), ('20', '20'), ('15', '15'), ('12', '12'), ('10', '10'), ('08', '08'), ('06', '06'), ('04', '04'), ('03', '03'), ('02', '02'), ('01', '01'), ('BU', 'BU'), ('CU', 'CU'), ('UNC', 'UNC'), ('AU+', 'AU+'), ('AU', 'AU'), ('XF+', 'XF+'), ('XF', 'XF'), ('VF+', 'VF+'), ('VF', 'VF'), ('F+', 'F+'), ('F', 'F'), ('VG+', 'VG+'), ('VG', 'VG'), ('G+', 'G+'), ('G', 'G')], default='70', max_length=3)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('dollar_type', models.CharField(choices=[('Flowing Hair Dollar', 'Flowing Hair Dollar'), ('Draped Bust Dollar', 'Draped Bust Dollar'), ('Liberty Seated Dollar', 'Liberty Seated Dollar'), ('Trade Dollar', 'Trade Dollar'), ('Morgan Dollar', 'Morgan Dollar'), ('Peace Dollar', 'Peace Dollar'), ('Ike Dollar', 'Ike Dollar'), ('Susan B. Anthony Dollar', 'Susan B. Anthony Dollar'), ('Sacagawea Dollar', 'Sacagawea Dollar'), ('Presidential Dollar', 'Presidential Dollar'), ('American Innovation Dollar', 'American Innovation Dollar')], max_length=30)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver_dollars', to='accounts.business')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver_dollar_sku', to='core.sku')),
            ],
            options={
                'verbose_name': 'Silver Dollar',
                'verbose_name_plural': 'Silver Dollars',
            },
        ),
        migrations.CreateModel(
            name='HalfDollars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mint', models.CharField(choices=[('P', 'Philadelphia Mint'), ('S', 'San Francisco Mint'), ('D', 'Denver Mint'), ('CC', 'Carson City Mint'), ('W', 'West Point Mint'), ('C', 'Charlotte Mint'), ('O', 'New Orleans Mint'), ('DL', 'Dahlonega Mint')], default='P', max_length=2)),
                ('pcgs_number', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('denomination', models.CharField(choices=[('$50', '$50'), ('$25', '$25'), ('$20', '$20'), ('$10', '$10'), ('$5', '$5'), ('$4', '$4'), ('$3', '$3'), ('$2.5', '$2.5'), ('$1', '$1'), ('50C', '50C'), ('25C', '25C'), ('20C', '20C'), ('10C', '10C'), ('5C', '5C'), ('3CN', '3CN'), ('3CS', '3CS'), ('2C', '2C'), ('1C', '1C'), ('H1C', 'H1C')], default='$1', max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('strike', models.CharField(choices=[('MS', 'Business/Mint State'), ('PR', 'Proof'), ('RPR', 'Reverse Proof'), ('PL', 'Proof Like'), ('DMPL', 'DMPL'), ('STN', 'Satin'), ('BRN', 'Burnished')], default='MS', max_length=4)),
                ('grading', models.CharField(choices=[('PCGS', 'PCGS'), ('NGC', 'NGC'), ('PCGSCAC', 'PCGS CAC'), ('NGCCAC', 'NGC CAC'), ('ANACS', 'ANACS'), ('ICG', 'ICG'), ('PCGSoNGC', 'PCGS or NGC'), ('PCGSoNGCaCAC', 'PCGS or NGC and CAC'), ('Ungraded', 'Ungraded')], default='PCGS', max_length=15)),
                ('grade', models.CharField(choices=[('70', '70'), ('69+', '69+'), ('69', '69'), ('68+', '68+'), ('68', '68'), ('67+', '67+'), ('67', '67'), ('66+', '66+'), ('66', '66'), ('65+', '65+'), ('65', '65'), ('64+', '64+'), ('64', '64'), ('63+', '63+'), ('63', '63'), ('62+', '62+'), ('62', '62'), ('61+', '61+'), ('61', '61'), ('60+', '60+'), ('60', '60'), ('58', '58'), ('55', '55'), ('50', '50'), ('45', '45'), ('40', '40'), ('35', '35'), ('30', '30'), ('25', '25'), ('20', '20'), ('15', '15'), ('12', '12'), ('10', '10'), ('08', '08'), ('06', '06'), ('04', '04'), ('03', '03'), ('02', '02'), ('01', '01'), ('BU', 'BU'), ('CU', 'CU'), ('UNC', 'UNC'), ('AU+', 'AU+'), ('AU', 'AU'), ('XF+', 'XF+'), ('XF', 'XF'), ('VF+', 'VF+'), ('VF', 'VF'), ('F+', 'F+'), ('F', 'F'), ('VG+', 'VG+'), ('VG', 'VG'), ('G+', 'G+'), ('G', 'G')], default='70', max_length=3)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('half_dollar_type', models.CharField(choices=[('Flowing Hair Half Dollar', 'Flowing Hair Half Dollar'), ('Draped Bust Half Dollar', 'Draped Bust Half Dollar'), ('Capped Bust Half Dollar', 'Capped Bust Half Dollar'), ('Liberty Seated Half Dollar', 'Liberty Seated Half Dollar'), ('Barber Half Dollar', 'Barber Half Dollar'), ('Walking Liberty Half Dollar', 'Walking Liberty Half Dollar'), ('Kennedy Half Dollar', 'Kennedy Half Dollar')], max_length=30)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half_dollars', to='accounts.business')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half_dollar_sku', to='core.sku')),
            ],
            options={
                'verbose_name': 'Half Dollar',
                'verbose_name_plural': 'Half Dollars',
            },
        ),
        migrations.CreateModel(
            name='BulkSilverDollars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('philadelphia', models.BooleanField(default=False)),
                ('san_francisco', models.BooleanField(default=False)),
                ('denver', models.BooleanField(default=False)),
                ('carson_city', models.BooleanField(default=False)),
                ('west_coast', models.BooleanField(default=False)),
                ('charlotte', models.BooleanField(default=False)),
                ('new_orleans', models.BooleanField(default=False)),
                ('dahlonega', models.BooleanField(default=False)),
                ('pcgs_number', models.IntegerField(blank=True, null=True)),
                ('year_1', models.IntegerField()),
                ('year_2', models.IntegerField(blank=True, null=True)),
                ('denomination', models.CharField(choices=[('$50', '$50'), ('$25', '$25'), ('$20', '$20'), ('$10', '$10'), ('$5', '$5'), ('$4', '$4'), ('$3', '$3'), ('$2.5', '$2.5'), ('$1', '$1'), ('50C', '50C'), ('25C', '25C'), ('20C', '20C'), ('10C', '10C'), ('5C', '5C'), ('3CN', '3CN'), ('3CS', '3CS'), ('2C', '2C'), ('1C', '1C'), ('H1C', 'H1C')], default='$1', max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('strike', models.CharField(choices=[('MS', 'Business/Mint State'), ('PR', 'Proof'), ('RPR', 'Reverse Proof'), ('PL', 'Proof Like'), ('DMPL', 'DMPL'), ('STN', 'Satin'), ('BRN', 'Burnished')], default='MS', max_length=4)),
                ('grading', models.CharField(choices=[('PCGS', 'PCGS'), ('NGC', 'NGC'), ('PCGSCAC', 'PCGS CAC'), ('NGCCAC', 'NGC CAC'), ('ANACS', 'ANACS'), ('ICG', 'ICG'), ('PCGSoNGC', 'PCGS or NGC'), ('PCGSoNGCaCAC', 'PCGS or NGC and CAC'), ('Ungraded', 'Ungraded')], default='PCGS', max_length=15)),
                ('grade_1', models.CharField(choices=[('70', '70'), ('69+', '69+'), ('69', '69'), ('68+', '68+'), ('68', '68'), ('67+', '67+'), ('67', '67'), ('66+', '66+'), ('66', '66'), ('65+', '65+'), ('65', '65'), ('64+', '64+'), ('64', '64'), ('63+', '63+'), ('63', '63'), ('62+', '62+'), ('62', '62'), ('61+', '61+'), ('61', '61'), ('60+', '60+'), ('60', '60'), ('58', '58'), ('55', '55'), ('50', '50'), ('45', '45'), ('40', '40'), ('35', '35'), ('30', '30'), ('25', '25'), ('20', '20'), ('15', '15'), ('12', '12'), ('10', '10'), ('08', '08'), ('06', '06'), ('04', '04'), ('03', '03'), ('02', '02'), ('01', '01'), ('BU', 'BU'), ('CU', 'CU'), ('UNC', 'UNC'), ('AU+', 'AU+'), ('AU', 'AU'), ('XF+', 'XF+'), ('XF', 'XF'), ('VF+', 'VF+'), ('VF', 'VF'), ('F+', 'F+'), ('F', 'F'), ('VG+', 'VG+'), ('VG', 'VG'), ('G+', 'G+'), ('G', 'G')], default='70', max_length=3)),
                ('grade_2', models.CharField(choices=[('70', '70'), ('69+', '69+'), ('69', '69'), ('68+', '68+'), ('68', '68'), ('67+', '67+'), ('67', '67'), ('66+', '66+'), ('66', '66'), ('65+', '65+'), ('65', '65'), ('64+', '64+'), ('64', '64'), ('63+', '63+'), ('63', '63'), ('62+', '62+'), ('62', '62'), ('61+', '61+'), ('61', '61'), ('60+', '60+'), ('60', '60'), ('58', '58'), ('55', '55'), ('50', '50'), ('45', '45'), ('40', '40'), ('35', '35'), ('30', '30'), ('25', '25'), ('20', '20'), ('15', '15'), ('12', '12'), ('10', '10'), ('08', '08'), ('06', '06'), ('04', '04'), ('03', '03'), ('02', '02'), ('01', '01'), ('BU', 'BU'), ('CU', 'CU'), ('UNC', 'UNC'), ('AU+', 'AU+'), ('AU', 'AU'), ('XF+', 'XF+'), ('XF', 'XF'), ('VF+', 'VF+'), ('VF', 'VF'), ('F+', 'F+'), ('F', 'F'), ('VG+', 'VG+'), ('VG', 'VG'), ('G+', 'G+'), ('G', 'G')], default='G', max_length=3)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('quantity', models.IntegerField(default=0)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('dollar_type', models.CharField(choices=[('Flowing Hair Dollar', 'Flowing Hair Dollar'), ('Draped Bust Dollar', 'Draped Bust Dollar'), ('Liberty Seated Dollar', 'Liberty Seated Dollar'), ('Trade Dollar', 'Trade Dollar'), ('Morgan Dollar', 'Morgan Dollar'), ('Peace Dollar', 'Peace Dollar'), ('Ike Dollar', 'Ike Dollar'), ('Susan B. Anthony Dollar', 'Susan B. Anthony Dollar'), ('Sacagawea Dollar', 'Sacagawea Dollar'), ('Presidential Dollar', 'Presidential Dollar'), ('American Innovation Dollar', 'American Innovation Dollar')], max_length=30)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_silver_dollars', to='accounts.business')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_silver_dollar_sku', to='core.sku')),
            ],
            options={
                'verbose_name': 'Bulk Silver Dollars',
                'verbose_name_plural': 'Bulk Silver Dollars',
            },
        ),
        migrations.CreateModel(
            name='BulkHalfDollars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('philadelphia', models.BooleanField(default=False)),
                ('san_francisco', models.BooleanField(default=False)),
                ('denver', models.BooleanField(default=False)),
                ('carson_city', models.BooleanField(default=False)),
                ('west_coast', models.BooleanField(default=False)),
                ('charlotte', models.BooleanField(default=False)),
                ('new_orleans', models.BooleanField(default=False)),
                ('dahlonega', models.BooleanField(default=False)),
                ('pcgs_number', models.IntegerField(blank=True, null=True)),
                ('year_1', models.IntegerField()),
                ('year_2', models.IntegerField(blank=True, null=True)),
                ('denomination', models.CharField(choices=[('$50', '$50'), ('$25', '$25'), ('$20', '$20'), ('$10', '$10'), ('$5', '$5'), ('$4', '$4'), ('$3', '$3'), ('$2.5', '$2.5'), ('$1', '$1'), ('50C', '50C'), ('25C', '25C'), ('20C', '20C'), ('10C', '10C'), ('5C', '5C'), ('3CN', '3CN'), ('3CS', '3CS'), ('2C', '2C'), ('1C', '1C'), ('H1C', 'H1C')], default='$1', max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('strike', models.CharField(choices=[('MS', 'Business/Mint State'), ('PR', 'Proof'), ('RPR', 'Reverse Proof'), ('PL', 'Proof Like'), ('DMPL', 'DMPL'), ('STN', 'Satin'), ('BRN', 'Burnished')], default='MS', max_length=4)),
                ('grading', models.CharField(choices=[('PCGS', 'PCGS'), ('NGC', 'NGC'), ('PCGSCAC', 'PCGS CAC'), ('NGCCAC', 'NGC CAC'), ('ANACS', 'ANACS'), ('ICG', 'ICG'), ('PCGSoNGC', 'PCGS or NGC'), ('PCGSoNGCaCAC', 'PCGS or NGC and CAC'), ('Ungraded', 'Ungraded')], default='PCGS', max_length=15)),
                ('grade_1', models.CharField(choices=[('70', '70'), ('69+', '69+'), ('69', '69'), ('68+', '68+'), ('68', '68'), ('67+', '67+'), ('67', '67'), ('66+', '66+'), ('66', '66'), ('65+', '65+'), ('65', '65'), ('64+', '64+'), ('64', '64'), ('63+', '63+'), ('63', '63'), ('62+', '62+'), ('62', '62'), ('61+', '61+'), ('61', '61'), ('60+', '60+'), ('60', '60'), ('58', '58'), ('55', '55'), ('50', '50'), ('45', '45'), ('40', '40'), ('35', '35'), ('30', '30'), ('25', '25'), ('20', '20'), ('15', '15'), ('12', '12'), ('10', '10'), ('08', '08'), ('06', '06'), ('04', '04'), ('03', '03'), ('02', '02'), ('01', '01'), ('BU', 'BU'), ('CU', 'CU'), ('UNC', 'UNC'), ('AU+', 'AU+'), ('AU', 'AU'), ('XF+', 'XF+'), ('XF', 'XF'), ('VF+', 'VF+'), ('VF', 'VF'), ('F+', 'F+'), ('F', 'F'), ('VG+', 'VG+'), ('VG', 'VG'), ('G+', 'G+'), ('G', 'G')], default='70', max_length=3)),
                ('grade_2', models.CharField(choices=[('70', '70'), ('69+', '69+'), ('69', '69'), ('68+', '68+'), ('68', '68'), ('67+', '67+'), ('67', '67'), ('66+', '66+'), ('66', '66'), ('65+', '65+'), ('65', '65'), ('64+', '64+'), ('64', '64'), ('63+', '63+'), ('63', '63'), ('62+', '62+'), ('62', '62'), ('61+', '61+'), ('61', '61'), ('60+', '60+'), ('60', '60'), ('58', '58'), ('55', '55'), ('50', '50'), ('45', '45'), ('40', '40'), ('35', '35'), ('30', '30'), ('25', '25'), ('20', '20'), ('15', '15'), ('12', '12'), ('10', '10'), ('08', '08'), ('06', '06'), ('04', '04'), ('03', '03'), ('02', '02'), ('01', '01'), ('BU', 'BU'), ('CU', 'CU'), ('UNC', 'UNC'), ('AU+', 'AU+'), ('AU', 'AU'), ('XF+', 'XF+'), ('XF', 'XF'), ('VF+', 'VF+'), ('VF', 'VF'), ('F+', 'F+'), ('F', 'F'), ('VG+', 'VG+'), ('VG', 'VG'), ('G+', 'G+'), ('G', 'G')], default='G', max_length=3)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('quantity', models.IntegerField(default=0)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('half_dollar_type', models.CharField(choices=[('Flowing Hair Half Dollar', 'Flowing Hair Half Dollar'), ('Draped Bust Half Dollar', 'Draped Bust Half Dollar'), ('Capped Bust Half Dollar', 'Capped Bust Half Dollar'), ('Liberty Seated Half Dollar', 'Liberty Seated Half Dollar'), ('Barber Half Dollar', 'Barber Half Dollar'), ('Walking Liberty Half Dollar', 'Walking Liberty Half Dollar'), ('Kennedy Half Dollar', 'Kennedy Half Dollar')], max_length=30)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_half_dollars', to='accounts.business')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_half_dollar_sku', to='core.sku')),
            ],
            options={
                'verbose_name': 'Bulk Half Dollars',
                'verbose_name_plural': 'Bulk Half Dollars',
            },
        ),
    ]
