# Generated by Django 4.2.2 on 2023-06-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkhalfdollars',
            name='denomination',
            field=models.CharField(default='50C', max_length=3),
        ),
        migrations.AlterField(
            model_name='bulksilverdollars',
            name='denomination',
            field=models.CharField(default='$1', max_length=2),
        ),
        migrations.AlterField(
            model_name='halfdollars',
            name='denomination',
            field=models.CharField(default='50C', max_length=3),
        ),
        migrations.AlterField(
            model_name='silverdollars',
            name='denomination',
            field=models.CharField(default='$1', max_length=2),
        ),
    ]
