# Generated by Django 4.2.2 on 2023-06-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_silverdollars_mint_bulksilverdollars'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulksilverdollars',
            name='pcgs_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
