# Generated by Django 4.2.2 on 2023-06-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('coins', '0002_alter_bulkhalfdollars_denomination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halfdollars',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='silverdollars',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bulkhalfdollars',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_half_dollar_sku', to='core.sku'),
        ),
        migrations.AlterField(
            model_name='bulksilverdollars',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_silver_dollar_sku', to='core.sku'),
        ),
        migrations.AlterField(
            model_name='halfdollars',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='half_dollar_sku', to='core.sku'),
        ),
        migrations.AlterField(
            model_name='silverdollars',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_dollar_sku', to='core.sku'),
        ),
    ]
