# Generated by Django 4.2.2 on 2023-06-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('coins', '0003_halfdollars_quantity_silverdollars_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.images'),
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.images'),
        ),
        migrations.AddField(
            model_name='halfdollars',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.images'),
        ),
        migrations.AddField(
            model_name='silverdollars',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.images'),
        ),
    ]
