# Generated by Django 4.2.2 on 2023-07-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('coins', '0003_alter_coinfamily_options_alter_cointypename_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strike', models.CharField(choices=[('MS', 'Business/Mint State'), ('PR', 'Proof'), ('RPR', 'Reverse Proof'), ('PL', 'Proof Like'), ('DMPL', 'DMPL'), ('STN', 'Satin'), ('BRN', 'Burnished')], default='MS', max_length=4)),
                ('pcgs_number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=80)),
                ('year', models.IntegerField()),
                ('year2', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grading', models.CharField(choices=[('PCGS', 'PCGS'), ('NGC', 'NGC'), ('PCGSCAC', 'PCGS CAC'), ('NGCCAC', 'NGC CAC'), ('ANACS', 'ANACS'), ('ICG', 'ICG'), ('PCGSoNGC', 'PCGS or NGC'), ('PCGSoNGCaCAC', 'PCGS or NGC and CAC'), ('Ungraded', 'Ungraded')], default='PCGS', max_length=15)),
                ('grade', models.CharField(choices=[('70', '70'), ('69+', '69+'), ('69', '69'), ('68+', '68+'), ('68', '68'), ('67+', '67+'), ('67', '67'), ('66+', '66+'), ('66', '66'), ('65+', '65+'), ('65', '65'), ('64+', '64+'), ('64', '64'), ('63+', '63+'), ('63', '63'), ('62+', '62+'), ('62', '62'), ('61+', '61+'), ('61', '61'), ('60+', '60+'), ('60', '60'), ('58', '58'), ('55', '55'), ('50', '50'), ('45', '45'), ('40', '40'), ('35', '35'), ('30', '30'), ('25', '25'), ('20', '20'), ('15', '15'), ('12', '12'), ('10', '10'), ('08', '08'), ('06', '06'), ('04', '04'), ('03', '03'), ('02', '02'), ('01', '01'), ('BU', 'BU'), ('CU', 'CU'), ('UNC', 'UNC'), ('AU+', 'AU+'), ('AU', 'AU'), ('XF+', 'XF+'), ('XF', 'XF'), ('VF+', 'VF+'), ('VF', 'VF'), ('F+', 'F+'), ('F', 'F'), ('VG+', 'VG+'), ('VG', 'VG'), ('G+', 'G+'), ('G', 'G')], default='70', max_length=3)),
                ('grade2', models.CharField(blank=True, choices=[('70', '70'), ('69+', '69+'), ('69', '69'), ('68+', '68+'), ('68', '68'), ('67+', '67+'), ('67', '67'), ('66+', '66+'), ('66', '66'), ('65+', '65+'), ('65', '65'), ('64+', '64+'), ('64', '64'), ('63+', '63+'), ('63', '63'), ('62+', '62+'), ('62', '62'), ('61+', '61+'), ('61', '61'), ('60+', '60+'), ('60', '60'), ('58', '58'), ('55', '55'), ('50', '50'), ('45', '45'), ('40', '40'), ('35', '35'), ('30', '30'), ('25', '25'), ('20', '20'), ('15', '15'), ('12', '12'), ('10', '10'), ('08', '08'), ('06', '06'), ('04', '04'), ('03', '03'), ('02', '02'), ('01', '01'), ('BU', 'BU'), ('CU', 'CU'), ('UNC', 'UNC'), ('AU+', 'AU+'), ('AU', 'AU'), ('XF+', 'XF+'), ('XF', 'XF'), ('VF+', 'VF+'), ('VF', 'VF'), ('F+', 'F+'), ('F', 'F'), ('VG+', 'VG+'), ('VG', 'VG'), ('G+', 'G+'), ('G', 'G')], default='G', max_length=3, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('quantity', models.IntegerField(default=1)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('coin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_type_name', to='coins.cointypename')),
                ('denomination_of_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denomination_of_this_coin', to='coins.denominations')),
                ('family_of_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_of_coin', to='coins.coinfamily')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
