# Generated by Django 4.2.2 on 2023-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_bulkhalfdollars_images_bulksilverdollars_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkhalfdollars',
            old_name='grade_1',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='bulkhalfdollars',
            old_name='year_1',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='bulksilverdollars',
            old_name='grade_1',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='bulksilverdollars',
            old_name='year_1',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='bulkhalfdollars',
            name='carson_city',
        ),
        migrations.RemoveField(
            model_name='bulkhalfdollars',
            name='charlotte',
        ),
        migrations.RemoveField(
            model_name='bulkhalfdollars',
            name='dahlonega',
        ),
        migrations.RemoveField(
            model_name='bulkhalfdollars',
            name='denver',
        ),
        migrations.RemoveField(
            model_name='bulkhalfdollars',
            name='new_orleans',
        ),
        migrations.RemoveField(
            model_name='bulkhalfdollars',
            name='philadelphia',
        ),
        migrations.RemoveField(
            model_name='bulkhalfdollars',
            name='san_francisco',
        ),
        migrations.RemoveField(
            model_name='bulkhalfdollars',
            name='west_coast',
        ),
        migrations.RemoveField(
            model_name='bulksilverdollars',
            name='carson_city',
        ),
        migrations.RemoveField(
            model_name='bulksilverdollars',
            name='charlotte',
        ),
        migrations.RemoveField(
            model_name='bulksilverdollars',
            name='dahlonega',
        ),
        migrations.RemoveField(
            model_name='bulksilverdollars',
            name='denver',
        ),
        migrations.RemoveField(
            model_name='bulksilverdollars',
            name='new_orleans',
        ),
        migrations.RemoveField(
            model_name='bulksilverdollars',
            name='philadelphia',
        ),
        migrations.RemoveField(
            model_name='bulksilverdollars',
            name='san_francisco',
        ),
        migrations.RemoveField(
            model_name='bulksilverdollars',
            name='west_coast',
        ),
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='mint',
            field=models.CharField(choices=[('P', 'Philadelphia Mint'), ('S', 'San Francisco Mint'), ('D', 'Denver Mint'), ('CC', 'Carson City Mint'), ('W', 'West Point Mint'), ('C', 'Charlotte Mint'), ('O', 'New Orleans Mint'), ('DL', 'Dahlonega Mint')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='mint',
            field=models.CharField(choices=[('P', 'Philadelphia Mint'), ('S', 'San Francisco Mint'), ('D', 'Denver Mint'), ('CC', 'Carson City Mint'), ('W', 'West Point Mint'), ('C', 'Charlotte Mint'), ('O', 'New Orleans Mint'), ('DL', 'Dahlonega Mint')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='bulkhalfdollars',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bulksilverdollars',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
