# Generated by Django 4.2.2 on 2023-07-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_coinbasemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectMints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philadelphia', models.BooleanField(default=False)),
                ('san_francisco', models.BooleanField(default=False)),
                ('denver', models.BooleanField(default=False)),
                ('carson_city', models.BooleanField(default=False)),
                ('west_coast', models.BooleanField(default=False)),
                ('charlotte', models.BooleanField(default=False)),
                ('new_orleans', models.BooleanField(default=False)),
                ('dahlonega', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='coinbasemodel',
            name='mint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mint', to='coins.selectmints'),
            preserve_default=False,
        ),
    ]
