# Generated by Django 4.2.2 on 2023-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_rename_grade_1_bulkhalfdollars_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='carson_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='charlotte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='dahlonega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='denver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='new_orleans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='philadelphia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='san_francisco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='west_coast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='carson_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='charlotte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='dahlonega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='denver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='new_orleans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='philadelphia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='san_francisco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='west_coast',
            field=models.BooleanField(default=False),
        ),
    ]
