# Generated by Django 4.2.2 on 2023-06-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_bulkhalfdollars_carson_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkhalfdollars',
            name='mint',
        ),
        migrations.RemoveField(
            model_name='bulksilverdollars',
            name='mint',
        ),
    ]
