# Generated by Django 4.2.2 on 2023-06-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_remove_bulkhalfdollars_mint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkhalfdollars',
            name='title',
            field=models.CharField(default='yay', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulksilverdollars',
            name='title',
            field=models.CharField(default='yay2', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='halfdollars',
            name='title',
            field=models.CharField(default='yay3', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silverdollars',
            name='title',
            field=models.CharField(default='yay4', max_length=80),
            preserve_default=False,
        ),
    ]
