# Generated by Django 4.2.2 on 2023-07-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0015_alter_cointypename_denominations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinfamily',
            old_name='type',
            new_name='family',
        ),
    ]
