# Generated by Django 4.2.2 on 2023-07-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0016_rename_type_coinfamily_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinfamily',
            old_name='family',
            new_name='type',
        ),
    ]
