# Generated by Django 4.2.2 on 2023-07-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0020_remove_coinbasemodel_mints_remove_coinbasemodel_mint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinbasemodel',
            name='mint',
            field=models.ManyToManyField(related_name='mint', to='coins.selectonemint'),
        ),
    ]
