# Generated by Django 4.2.2 on 2023-07-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0023_alter_selectonemint_coin_mint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingservices',
            name='name',
            field=models.CharField(choices=[('PCGS', 'PCGS'), ('NGC', 'NGC'), ('PCGS CAC', 'PCGS CAC'), ('NGC CAC', 'NGC CAC'), ('ANACS', 'ANACS'), ('ICG', 'ICG'), ('PCGS or NGC', 'PCGS or NGC'), ('PCGS or NGC and CAC', 'PCGS or NGC and CAC'), ('Ungraded', 'Ungraded')], default='PCGS', max_length=32, unique=True),
        ),
    ]
