# Generated by Django 4.2.2 on 2023-07-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0024_alter_gradingservices_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingservices',
            name='name',
            field=models.CharField(choices=[('PCGS', 'PCGS'), ('NGC', 'NGC'), ('CAC', 'CAC'), ('ANACS', 'ANACS'), ('ICG', 'ICG'), ('Ungraded', 'Ungraded')], default='PCGS', max_length=32, unique=True),
        ),
    ]
