# Generated by Django 4.2.2 on 2023-08-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0031_mintsettypesmodel_mintproductsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mintproductsmodel',
            name='mint_set_name',
        ),
    ]
