# Generated by Django 4.2.2 on 2023-08-22 16:44

from django.db import migrations
from coins.data.grades import GRADES


def populate_coin_grades(apps, schema_editor):
    grades = apps.get_model("coins", "CoinGrades")

    for grade, _ in GRADES:
        grades.objects.get_or_create(grade=grade)


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0001_squashed_0032_remove_mintproductsmodel_mint_set_name"),
    ]

    operations = [
        migrations.RunPython(populate_coin_grades),
    ]
