# Generated by Django 4.2.2 on 2023-08-22 16:56

from django.db import migrations
from coins.data.grades import GRADING_SERVICES
from coins.models.strike import STRIKE
from coins.models.mints import MINTS
from coins.models.denominations import FAMILY_CHOICES


def populate_grading_services(apps, schema_editor):
    grading_services = apps.get_model("coins", "GradingServices")

    for service, _ in GRADING_SERVICES:
        grading_services.objects.get_or_create(name=service)


def populate_strikes(apps, schema_editor):
    strikes = apps.get_model("coins", "Strike")

    for strike, _ in STRIKE:
        strikes.objects.get_or_create(strike=strike)


def populate_mints(apps, schema_editor):
    mints = apps.get_model("coins", "SelectOneMint")

    for mint, _ in MINTS:
        mints.objects.get_or_create(coin_mint=mint)


def populate_family(apps, schema_editor):
    family = apps.get_model("coins", "CoinFamily")

    for fam, _ in FAMILY_CHOICES:
        family.objects.get_or_create(type=fam)


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0033_auto_20230822_1644"),
    ]

    operations = [
        migrations.RunPython(populate_grading_services),
        migrations.RunPython(populate_strikes),
        migrations.RunPython(populate_mints),
        migrations.RunPython(populate_family),
    ]
