# Generated by Django 4.2.2 on 2023-08-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0034_auto_20230822_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinfamily',
            name='type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Clad', 'Clad'), ('Copper', 'Copper'), ('Nickel', 'Nickel')], max_length=20, unique=True),
        ),
    ]
