# Generated by Django 4.2.2 on 2023-08-24 03:24

from django.db import migrations
from coins.models.denominations import (
    GOLD_DENOM,
    SILVER_DENOM,
    COPPER_DENOM,
    NICKEL_DENOM,
    CLAD_DENOM,
)


def populate_gold_denoms(apps, schema_editor):
    CoinFamily = apps.get_model("coins", "CoinFamily")
    Denominations = apps.get_model("coins", "Denominations")

    gold_family = CoinFamily.objects.get(type="Gold")

    for denom, _ in GOLD_DENOM:
        Denominations.objects.get_or_create(
            denomination_of_coin=denom,
            family=gold_family,
        )


def populate_silver_denoms(apps, schema_editor):
    CoinFamily = apps.get_model("coins", "CoinFamily")
    Denominations = apps.get_model("coins", "Denominations")

    silver_family = CoinFamily.objects.get(type="Silver")

    for denom, _ in SILVER_DENOM:
        Denominations.objects.get_or_create(
            denomination_of_coin=denom,
            family=silver_family,
        )


def populate_copper_denoms(apps, schema_editor):
    CoinFamily = apps.get_model("coins", "CoinFamily")
    Denominations = apps.get_model("coins", "Denominations")

    copper_family = CoinFamily.objects.get(type="Copper")

    for denom, _ in COPPER_DENOM:
        Denominations.objects.get_or_create(
            denomination_of_coin=denom,
            family=copper_family,
        )


def populate_nickel_denoms(apps, schema_editor):
    CoinFamily = apps.get_model("coins", "CoinFamily")
    Denominations = apps.get_model("coins", "Denominations")

    nickel_family = CoinFamily.objects.get(type="Nickel")

    for denom, _ in NICKEL_DENOM:
        Denominations.objects.get_or_create(
            denomination_of_coin=denom,
            family=nickel_family,
        )


def populate_clad_denoms(apps, schema_editor):
    CoinFamily = apps.get_model("coins", "CoinFamily")
    Denominations = apps.get_model("coins", "Denominations")

    clad_family = CoinFamily.objects.get(type="Clad")

    for denom, _ in CLAD_DENOM:
        Denominations.objects.get_or_create(
            denomination_of_coin=denom,
            family=clad_family,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0036_alter_coinbasemodel_sku_ptr"),
    ]

    operations = [
        migrations.RunPython(populate_gold_denoms),
        migrations.RunPython(populate_silver_denoms),
        migrations.RunPython(populate_copper_denoms),
        migrations.RunPython(populate_nickel_denoms),
        migrations.RunPython(populate_clad_denoms),
    ]
