# Generated by Django 4.2.2 on 2023-08-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0037_auto_20230824_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominations',
            name='denomination_of_coin',
            field=models.CharField(choices=[('$50', '$50'), ('$25', '$25'), ('$20', '$20'), ('$10', '$10'), ('$5', '$5'), ('$4', '$4'), ('$3', '$3'), ('$2.5', '$2.5'), ('$1', '$1'), ('50C', '50C'), ('25C', '25C'), ('20C', '20C'), ('10C', '10C'), ('H10C', 'H10C'), ('5C', '5C'), ('3CN', '3CN'), ('3CS', '3CS'), ('2C', '2C'), ('1C', '1C'), ('H1C', 'H1C')], default='$1', max_length=4),
        ),
    ]
