# Generated by Django 4.2.2 on 2023-08-24 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0038_alter_denominations_denomination_of_coin"),
    ]

    operations = []
