# Generated by Django 4.2.2 on 2023-08-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0039_auto_20230824_0411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cointypename",
            name="coin_type",
            field=models.CharField(max_length=100),
        ),
    ]
