# Generated by Django 4.2.2 on 2023-08-24 04:22

from django.db import migrations


half_cents = [
    "Liberty Cap Half Cent",
    "Draped Bust Half Cent",
    "Classic Head Half Cent",
    "Braided Hair Half Cent",
]


def populate_half_cents(apps, schema_editor):
    Name = apps.get_model("coins", "CoinTypeName")
    Denom = apps.get_model("coins", "Denominations")

    hc_d = Denom.objects.get(denomination_of_coin="H1C", family__type="Copper")

    for hc in half_cents:
        Name.objects.get_or_create(coin_type=hc, denominations=hc_d)


cents = [
    "Flowing Hair Large Cent",
    "Draped Bust Cent",
    "Classic Head Cent",
    "Coronet Head Cent",
    "Braided Hair Cent",
    "Flying Eagle Cent",
    "Indian Cent",
    "Lincoln Cent (Wheat Reverse)",
    "Lincoln Cent (Modern)",
]


def populate_cents(apps, schema_editor):
    Name = apps.get_model("coins", "CoinTypeName")
    denom = apps.get_model("coins", "Denominations")

    c_d = denom.objects.get(denomination_of_coin="1C", family__type="Copper")

    for cent in cents:
        Name.objects.get_or_create(coin_type=cent, denominations=c_d)


two_cent = ["Two Cent"]


def populate_two_cent(apps, schema_editor):
    name = apps.get_model("coins", "CoinTypeName")
    denom = apps.get_model("coins", "Denominations")

    t_d = denom.objects.get(denomination_of_coin="2C", family__type="Copper")

    for c in two_cent:
        name.objects.get_or_create(coin_type=c, denominations=t_d)


three_c_s = ["Three Cent Silver"]


def populate_three_silver(apps, schema_editor):
    name = apps.get_model("coins", "CoinTypeName")
    denom = apps.get_model("coins", "Denominations")

    t_c_s = denom.objects.get(denomination_of_coin="3CS", family__type="Silver")

    for tcs in three_c_s:
        name.objects.get_or_create(coin_type=tcs, denominations=t_c_s)


three_c_n = ["Three Cent Nickel"]


def populate_three_nickel(apps, schema_editor):
    name = apps.get_model("coins", "CoinTypeName")
    denom = apps.get_model("coins", "Denominations")

    t_c_n = denom.objects.get(denomination_of_coin="3CN", family__type="Nickel")

    for tcn in three_c_n:
        name.objects.get_or_create(coin_type=tcn, denominations=t_c_n)


def populate(apps, schema_editor, denom_of_coin, family, list_of_names):
    name = apps.get_model("coins", "CoinTypeName")
    denom = apps.get_model("coins", "Denominations")

    denom2 = denom.objects.get(
        denomination_of_coin=denom_of_coin,
        family__type=family,
    )

    for coin_type in list_of_names:
        name.objects.get_or_create(coin_type=coin_type, denominations=denom2)


silver_dollars = [
    "Flowing Hair Dollar",
    "Draped Bust Dollar",
    "Liberty Seated Dollar",
    "Trade Dollar",
    "Morgan Dollar",
    "Peace Dollar",
    "Ike Dollar",
]


def populate_silver_dollars(apps, schema_editor):
    Name = apps.get_model("coins", "CoinTypeName")
    Denom = apps.get_model("coins", "Denominations")

    silver_denom = Denom.objects.get(
        denomination_of_coin="$1",
        family__type="Silver",
    )

    for silver_dollar in silver_dollars:
        Name.objects.get_or_create(
            coin_type=silver_dollar,
            denominations=silver_denom,
        )


gold_dollars = [
    "Gold Dollar",
]


def populate_gold_dollars(apps, schema_editor):
    Name = apps.get_model("coins", "CoinTypeName")
    Denom = apps.get_model("coins", "Denominations")

    gold_denom = Denom.objects.get(
        denomination_of_coin="$1",
        family__type="Gold",
    )

    for gold_dollar in gold_dollars:
        Name.objects.get_or_create(
            coin_type=gold_dollar,
            denominations=gold_denom,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0040_alter_cointypename_coin_type"),
    ]

    operations = [
        migrations.RunPython(populate_half_cents),
        migrations.RunPython(populate_cents),
        migrations.RunPython(populate_two_cent),
        migrations.RunPython(populate_three_silver),
        migrations.RunPython(populate_three_nickel),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="5C",
                family="Nickel",
                list_of_names=[
                    "Shield Nickel",
                    "Liberty Nickel",
                    "Buffalo Nickel",
                    "Jefferson Nickel",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="H10C",
                family="Silver",
                list_of_names=[
                    "Bust Half Dime",
                    "Flowing Hair Half Dime",
                    "Draped Bust Half Dime",
                    "Capped Bust Half Dime",
                    "Liberty Seated Half Dime",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="10C",
                family="Clad",
                list_of_names=[
                    "Roosevelt Dime",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="10C",
                family="Silver",
                list_of_names=[
                    "Draped Bust Dime",
                    "Capped Bust Dime",
                    "Liberty Seated Dime",
                    "Barber Dime",
                    "Mercury Dime",
                    "Roosevelt Dime",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="20C",
                family="Silver",
                list_of_names=[
                    "Twenty Cent",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="25C",
                family="Silver",
                list_of_names=[
                    "Draped Bust Quarter",
                    "Capped Bust Quarter",
                    "Liberty Seated Quarter",
                    "Barber Quarter",
                    "Standing Liberty Quarter",
                    "Washington Quarter",
                    "Washington 50 States Quarters",
                    "Washington D.C. and U.S. Territories Quarters",
                    "Washington America the Beautiful Quarters",
                    "Washington Crossing the Delaware Quarters",
                    "American Women Quarters",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="25C",
                family="Clad",
                list_of_names=[
                    "Washington Quarter",
                    "Washington 50 States Quarters",
                    "Washington D.C. and U.S. Territories Quarters",
                    "Washington America the Beautiful Quarters",
                    "Washington Crossing the Delaware Quarters",
                    "American Women Quarters",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="50C",
                family="Clad",
                list_of_names=[
                    "Kennedy Half Dollar",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="50C",
                family="Silver",
                list_of_names=[
                    "Flowing Hair Half Dollar",
                    "Draped Bust Half Dollar",
                    "Capped Bust Half Dollar",
                    "Liberty Seated Half Dollar",
                    "Barber Half Dollar",
                    "Walking Liberty Half Dollar",
                    "Franklin Half Dollar",
                    "Kennedy Half Dollar",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="$1",
                family="Clad",
                list_of_names=[
                    "Ike Dollar",
                    "Susan B. Anthony",
                    "Sacagawea Dollar",
                    "Presidential Dollars",
                    "American Innovation Dollar",
                ],
            ),
        ),
        migrations.RunPython(populate_silver_dollars),
        migrations.RunPython(populate_gold_dollars),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="$2.5",
                family="Gold",
                list_of_names=[
                    "Draped Bust $2.5",
                    "Capped Bust $2.5",
                    "Classic Head $2.5",
                    "liberty Head $2.5",
                    "Indian $2.5",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="$3",
                family="Gold",
                list_of_names=[
                    "Three Dollar",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="$4",
                family="Gold",
                list_of_names=[
                    "$4 Stella",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="$5",
                family="Gold",
                list_of_names=[
                    "Draped Bust $5",
                    "Capped Bust $5",
                    "Classic Head $5",
                    "Liberty Head $5",
                    "Indian $5",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="$10",
                family="Gold",
                list_of_names=[
                    "Draped Bust $10",
                    "Liberty Head $10",
                    "Indian $10",
                ],
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: populate(
                apps,
                schema_editor,
                denom_of_coin="$20",
                family="Gold",
                list_of_names=[
                    "Liberty Head $20",
                    "St. Gaudens $20",
                ],
            ),
        ),
    ]
