# Generated by Django 4.2.2 on 2023-08-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0041_auto_20230824_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinfamily',
            name='type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Clad', 'Clad'), ('Nickel', 'Nickel'), ('Copper', 'Copper')], max_length=20, unique=True),
        ),
    ]
