# Generated by Django 5.0.2 on 2024-02-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0042_alter_coinfamily_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinbasemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
