# Generated by Django 5.0.2 on 2024-03-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stripecustomer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripecustomer',
            options={'verbose_name_plural': 'Stripe Customers'},
        ),
    ]
