# Generated by Django 4.2.2 on 2023-08-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={},
        ),
        migrations.AddField(
            model_name='customers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
