# Generated by Django 5.0.2 on 2024-06-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_customer_stripetenantcustomer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripetenantcustomer',
            options={'verbose_name': 'Stripe Tenant Customer', 'verbose_name_plural': 'Stripe Tenant Customers'},
        ),
    ]
