# Generated by Django 4.2.2 on 2023-09-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='invoice_number',
        ),
    ]
