# Generated by Django 4.2.2 on 2023-09-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_options_customers_is_deleted'),
        ('invoice', '0005_remove_salesinvoice_customer_salesinvoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customers.customers'),
        ),
    ]
