# Generated by Django 5.0.2 on 2024-06-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_salesinvoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
