# Generated by Django 5.0.2 on 2024-06-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_salesinvoice_sales_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
